/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SEApplication;

/**
 *
 * @author Thiwanka
 */
public class SE_App extends javax.swing.JFrame {

    /**
     * Creates new form SE_App
     */
    public SE_App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TypeSelector = new javax.swing.JComboBox<>();
        Price = new javax.swing.JLabel();
        Calculatetotal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        whipping = new javax.swing.JCheckBox();
        vanilla = new javax.swing.JCheckBox();
        cashew = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decorator Pattern Test");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fresh Fruit");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fruit Juice Type");

        TypeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orange", "Avacado", "Strawberry", "Pomegranatc" }));
        TypeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeSelectorActionPerformed(evt);
            }
        });

        Price.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(255, 0, 51));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("Type Of Order");

        Calculatetotal.setBackground(new java.awt.Color(204, 0, 51));
        Calculatetotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Calculatetotal.setText("Calculate Total");
        Calculatetotal.setContentAreaFilled(false);
        Calculatetotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculatetotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatetotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Toppings");

        total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 0, 51));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("00.00");

        whipping.setText("Whipping Cream");
        whipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whippingActionPerformed(evt);
            }
        });

        vanilla.setText("Vanilla Cream");
        vanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillaActionPerformed(evt);
            }
        });

        cashew.setText("Cashew Nuts");
        cashew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashewActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fruit-juice.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cashew, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(whipping, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vanilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Calculatetotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TypeSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(whipping)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cashew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(vanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Calculatetotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TypeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeSelectorActionPerformed

    private void CalculatetotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatetotalActionPerformed
       
        //Orange
        
        if(TypeSelector.getSelectedItem().equals("Orange")||whipping.isSelected()||vanilla.isSelected()||cashew.isSelected()){
            if(TypeSelector.getSelectedItem().equals("Orange")){
                FruitJuice fj = new Orange();
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Orange();
                String d1 = des1.getDes();
                Price.setText(d1);
                
            }
            if(TypeSelector.getSelectedItem().equals("Orange")&&whipping.isSelected()){
                FruitJuice fj = new Orange();
                fj= new WhippingCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1);
                
                FruitJuice des1 = new Orange();
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Orange")&&vanilla.isSelected()){
                FruitJuice fj = new Orange();
                fj= new VanillaCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                 FruitJuice des1 = new Orange();
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Orange")&&cashew.isSelected()){
             FruitJuice fj = new Orange();
                fj= new CashewNuts(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Orange();
                des1= new CashewNuts(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Orange")&&cashew.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Orange();
                 fj1= new CashewNuts(fj1);
                 fj1 =new WhippingCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Orange();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Orange")&&cashew.isSelected()&&vanilla.isSelected()){
                 FruitJuice fj1 = new Orange();
                 fj1= new CashewNuts(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Orange();
                des1= new CashewNuts(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Orange")&&vanilla.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Orange();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Orange();
                des1= new VanillaCream(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
                
             }  if(TypeSelector.getSelectedItem().equals("Orange")&&vanilla.isSelected()&&whipping.isSelected()&&cashew.isSelected()){
                 FruitJuice fj1 = new Orange();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                 fj1 = new CashewNuts(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Orange();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
        
        }
             //Avacado
             
         if(TypeSelector.getSelectedItem().equals("Avacado")||whipping.isSelected()||vanilla.isSelected()||cashew.isSelected()){
            if(TypeSelector.getSelectedItem().equals("Avacado")){
                FruitJuice fj = new Avacado();
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Avacado();
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Avacado")&&whipping.isSelected()){
                FruitJuice fj = new Avacado();
                fj= new WhippingCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1);
                
                FruitJuice des1 = new Avacado();
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Avacado")&&vanilla.isSelected()){
                FruitJuice fj = new Avacado();
                fj= new VanillaCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Avacado();
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Avacado")&&cashew.isSelected()){
             FruitJuice fj = new Avacado();
                fj= new CashewNuts(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Avacado();
                des1= new CashewNuts(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Avacado")&&cashew.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Avacado();
                 fj1= new CashewNuts(fj1);
                 fj1 =new WhippingCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Avacado();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Avacado")&&cashew.isSelected()&&vanilla.isSelected()){
                 FruitJuice fj1 = new Avacado();
                 fj1= new CashewNuts(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Avacado();
                des1= new CashewNuts(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Avacado")&&vanilla.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Avacado();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Avacado();
                des1= new VanillaCream(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             }  if(TypeSelector.getSelectedItem().equals("Avacado")&&vanilla.isSelected()&&whipping.isSelected()&&cashew.isSelected()){
                 FruitJuice fj1 = new Avacado();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                 fj1 = new CashewNuts(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Avacado();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
        
        }
             //Strawbery
             
        if(TypeSelector.getSelectedItem().equals("Strawberry")||whipping.isSelected()||vanilla.isSelected()||cashew.isSelected()){
            if(TypeSelector.getSelectedItem().equals("Strawberry")){
                FruitJuice fj = new Strawberry();
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Strawberry();
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Strawberry")&&whipping.isSelected()){
                FruitJuice fj = new Strawberry();
                fj= new WhippingCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1);
                
                FruitJuice des1 = new Strawberry();
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Strawberry")&&vanilla.isSelected()){
                FruitJuice fj = new Strawberry();
                fj= new VanillaCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Strawberry();                
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Strawberry")&&cashew.isSelected()){
             FruitJuice fj = new Strawberry();
                fj= new CashewNuts(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Strawberry();
                des1= new CashewNuts(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Strawberry")&&cashew.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Strawberry();
                 fj1= new CashewNuts(fj1);
                 fj1 =new WhippingCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Strawberry();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Strawberry")&&cashew.isSelected()&&vanilla.isSelected()){
                 FruitJuice fj1 = new Strawberry();
                 fj1= new CashewNuts(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Strawberry();
                des1= new CashewNuts(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Strawberry")&&vanilla.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Strawberry();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Strawberry();
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             }  if(TypeSelector.getSelectedItem().equals("Strawberry")&&vanilla.isSelected()&&whipping.isSelected()&&cashew.isSelected()){
                 FruitJuice fj1 = new Strawberry();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                 fj1 = new CashewNuts(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Strawberry();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
        
        }
        
        //Pomegranatc
        if(TypeSelector.getSelectedItem().equals("Pomegranatc")||whipping.isSelected()||vanilla.isSelected()||cashew.isSelected()){
            if(TypeSelector.getSelectedItem().equals("Pomegranatc")){
                FruitJuice fj = new Pomegranate();
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Pomegranate();
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&whipping.isSelected()){
                FruitJuice fj = new Pomegranate();
                fj= new WhippingCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1);
                
                FruitJuice des1 = new Pomegranate();
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&vanilla.isSelected()){
                FruitJuice fj = new Pomegranate();
                fj= new VanillaCream(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Pomegranate();
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
            if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&cashew.isSelected()){
             FruitJuice fj = new Pomegranate();
                fj= new CashewNuts(fj);
                String t1 =String.valueOf(fj.getPrice());
                total.setText(t1); 
                
                FruitJuice des1 = new Pomegranate();
                des1= new CashewNuts(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
            }
             if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&cashew.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Pomegranate();
                 fj1= new CashewNuts(fj1);
                 fj1 =new WhippingCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Pomegranate();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&cashew.isSelected()&&vanilla.isSelected()){
                 FruitJuice fj1 = new Pomegranate();
                 fj1= new CashewNuts(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Pomegranate();
                des1= new CashewNuts(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
             if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&vanilla.isSelected()&&whipping.isSelected()){
                 FruitJuice fj1 = new Pomegranate();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Pomegranate();
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
                
             }  if(TypeSelector.getSelectedItem().equals("Pomegranatc")&&vanilla.isSelected()&&whipping.isSelected()&&cashew.isSelected()){
                 FruitJuice fj1 = new Pomegranate();
                 fj1= new WhippingCream(fj1);
                 fj1 =new VanillaCream(fj1);
                 fj1 = new CashewNuts(fj1);
                String t2 =String.valueOf(fj1.getPrice());
                total.setText(t2);
                
                FruitJuice des1 = new Pomegranate();
                des1= new CashewNuts(des1);
                des1= new WhippingCream(des1);
                des1= new VanillaCream(des1);
                String d1 = des1.getDes();
                Price.setText(d1);
             } 
        
        }

    }//GEN-LAST:event_CalculatetotalActionPerformed

    private void whippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whippingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whippingActionPerformed

    private void cashewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashewActionPerformed

    private void vanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vanillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SE_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SE_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SE_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SE_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SE_App().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculatetotal;
    private javax.swing.JLabel Price;
    private javax.swing.JComboBox<String> TypeSelector;
    private javax.swing.JCheckBox cashew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel total;
    private javax.swing.JCheckBox vanilla;
    private javax.swing.JCheckBox whipping;
    // End of variables declaration//GEN-END:variables
}
interface  FruitJuice{//Component
    public abstract double getPrice();
    public abstract String getDes();
    
}
class Orange implements FruitJuice{//SubComponent (IS-A)
    @Override
    public double getPrice(){
        return 100;
    }
    @Override
    public String getDes(){
        return "Orange";
    }
}class Avacado implements FruitJuice{
    @Override
    public double  getPrice(){
        return 120;
    }

    @Override
    public String getDes() {
       return "Avacado";
    }
}
class Strawberry implements FruitJuice{
    @Override
    public double  getPrice(){
        return 200;
    }

    @Override
    public String getDes() {
        return "Strawberry";
    }
}
class Pomegranate implements FruitJuice{
    @Override
    public double  getPrice(){
        return 250;
    }

    @Override
    public String getDes() {
        return "Pomegranate";
    }
}
abstract class Toppings implements FruitJuice{//Decorator (IS-A)
    private final FruitJuice fruitJuice;    //HAS_A

    public Toppings(FruitJuice fruitJuice) {//Decorator must has a icecream therefor we create constructor in decorator class (Because before add chocolate sause must has a icecream)
        this.fruitJuice = fruitJuice;
    }
    @Override
    public double getPrice(){
        return fruitJuice.getPrice();
    }
    @Override
    public String getDes(){
        return fruitJuice.getDes();
    }
    
}
 class WhippingCream extends Toppings{//SubDecorator (IS-A)
    
     public WhippingCream(FruitJuice fruitJuice) {//child class must inherit super class everythings,Therefor it must has constructor
         super(fruitJuice);//child class call supper class
     }

    @Override
    public double getPrice() {
        return super.getPrice()+20;
    }
     @Override
    public String getDes(){
        return super.getDes()+" Whipping Cream " ;
    }
    
}
 class VanillaCream extends Toppings{//SubDecorator (IS-A)
    
     public VanillaCream(FruitJuice fruitJuice) {//child class must inherit super class everythings,Therefor it must has constructor
         super(fruitJuice);//child class call supper class
     }

    @Override
    public double getPrice() {
        return super.getPrice()+50;
    }
     @Override
    public String getDes(){
        return super.getDes()+" Vanilla Cream " ;
    }
    
}
 class CashewNuts extends Toppings{//SubDecorator (IS-A)
    
     public CashewNuts(FruitJuice fruitJuice) {//child class must inherit super class everythings,Therefor it must has constructor
         super(fruitJuice);//child class call supper class
     }

    @Override
    public double getPrice() {
        return super.getPrice()+10;
    }
     @Override
    public String getDes(){
        return super.getDes()+" Cashew Nuts " ;
    }
    
}
